project:
  type: book
  output-dir: "docs"
  preview:
    port: 1313

execute: 
  freeze: auto
  cache: true
  daemon: 3600

website:
  favicon: img/logos/favicon.ico
  reader-mode: true
  comments: 
    hypothesis:
      theme: clean
      openSidebar: true

book:
  title: "Manual de Estadística"
  subtitle: "para Ciencias e Ingenierías"
  author: "Alfredo Sánchez Alberca"
  date: "1/6/2022"
  output-file: "manual-estadistica"
  image: img/logos/sticker.png
  cover-image: img/logos/sticker.png
  sharing: [twitter, linkedin]
  downloads: [pdf, epub]
  favicon: "img/logos/favicon.ico"
  sidebar:
    logo: img/logos/aprendeconalf.png
    tools:
      - icon: house-fill
        href: https://aprendeconalf.es
  open-graph: true
  twitter-card: 
    site: "@aprendeconalf"
  chapters:
    - index.qmd
    - 01-introduccion.qmd
    - 02-estadistica-descriptiva.qmd
    - 03-regresion.qmd
    - 04-relaciones-cualitativas.qmd
    - 05-probabilidad.qmd
    # - 05-variables-aletaorias-discretas.qmd
    # - 06-variables-aleatorias-continuas.qmd
    - 08-estimacion.qmd
    - 09-contrastes-parametricos.qmd
    
#bibliography: references.bib

format:
  html:
    highlight-style: a11y
    theme:
      dark: [darkly, custom-dark.scss]
      light: [flatly, custom.scss]
    html-math-method: mathjax
  pdf:
    documentclass: scrreport
    papersize: a4
    template-partials:
      - before-body.tex
    titlegraphic: img/logos/sticker.png
    institution: CEU San Pablo
    email: asalber@ceu.es
    web: https://aprendeconalf.es
    logo: img/logos/aprendeconalf.png
    include-in-header:
      - preamble.tex
      - macros.tex
    keep-tex: true
    #mainfont: TeX Gyre Termes
    #mainfontoptions:
    #  - Numbers=Lowercase
    #  - Numbers=Proportional    
    
  epub:
    cover-image: img/logos/sticker.png
    html-math-method: mathml
    toc: true




