{
  "hash": "25b11a143becc943e7de76821d2826e8",
  "result": {
    "markdown": "---\ntitle: Estadística Descriptiva\nlang: es\n---\n\n\n\n\n\n\nLa estadística descriptiva es la parte de la estadística encargada de representar, analizar y resumir la información contenida en la muestra.\n\nTras el proceso de muestreo, es la siguiente etapa de todo estudio estadístico y suele consistir en:\n\n1. Clasificar, agrupar y ordenar los datos de la muestra.\n\n2. Tabular y representar gráficamente los datos de acuerdo a sus frecuencias.\n\n3. Calcular medidas que resuman la información que contiene la muestra (_estadísticos muestrales_).\n\n:::{.callout-note title=\"Interpretación\"}\nNo tiene poder inferencial, por lo que nunca deben sacarse conclusiones sobre la población a partir de las medidas resumen que aporta la Estadística Descriptiva.\n:::\n\n## Distribución de frecuencias\n\nEl estudio de una variable estadística comienza por medir la variable en los individuos de la muestra y clasificar los valores obtenidos.\n\nExisten dos formas de clasificar estos valores:\n\n- **Sin agrupar**: Ordenar todos los valores obtenidos en la muestra de menor a mayor. Se utiliza con atributos y variables discretas con pocos valores diferentes.\n\n- **Agrupados**: Agrupar los valores en clases (intervalos) y ordenar dichas clases de menor a mayor. Se utiliza con variables continuas y con variables discretas con muchos valores diferentes.\n\n### Clasificación de la muestra\n\nConsiste colocar juntos los valores iguales y ordenarlos si existe un orden entre ellos.\n\n![Clasificación de la muestra.](img/descriptiva/clasificacion_muestra.png)\n\n### Recuento de frecuencias\n\n![Recuento de frecuencias](img/descriptiva/recuento_frecuencias.png)\n\n## Frecuencias muestrales\n\n:::{#def-frecuencias-muestrales}\n## Frecuencias muestrales\nDada una muestra de tamaño $n$ de una variable $X$, para cada valor de la variable $x_i$ observado en la muestra, se define\n\n- **Frecuencia Absoluta $n_i$**: Es el número de veces que el valor $x_i$ aparece en la muestra.\n- **Frecuencia Relativa $f_i$**: Es la proporción de veces que el valor $x_i$ aparece en la muestra.\n$$f_i = \\frac{n_i}{n}$$\n- **Frecuencia Absoluta Acumulada $N_i$**: Es el número de valores en la muestra menores o iguales que $x_i$.\n$$N_i = n_1 + \\cdots + n_i = N_{i-1}+n_i$$\n- **Frecuencia Relativa Acumulada $F_i$**: Es la proporción de valores en la muestra menores o iguales que $x_i$.\n$$F_i = \\frac{N_i}{n}$$\n:::\n\n### Tabla de frecuencias\n\nAl conjunto de valores observados en la muestra junto a sus respectivas frecuencias se le denomina **distribución de frecuencias** y suele representarse mediante una **tabla de frecuencias**.\n\n| Valores de $X$ | Frecuencia Absoluta | Frecuencia Relativa | Frecuencia Absoluta Acumulada | Frecuencia Relativa Acumulada |\n| :------------: | :-----------------: | :-----------------: | :---------------------------: | :---------------------------: |\n|     $x_1$      |        $n_1$        |        $f_1$        |             $N_1$             |             $F_1$             |\n|    $\\vdots$    |      $\\vdots$       |      $\\vdots$       |           $\\vdots$            |           $\\vdots$            |\n|     $x_i$      |        $n_i$        |        $f_i$        |             $N_i$             |             $F_i$             |\n|    $\\vdots$    |      $\\vdots$       |      $\\vdots$       |           $\\vdots$            |           $\\vdots$            |\n|     $x_k$      |        $n_k$        |        $f_k$        |             $N_k$             |             $F_k$             |\n\n:::{#exm-tabla-frecuencias-datos-no-agrupados}\n## Variable cuantitativa y datos no agrupados\nEl número de hijos en 25 familias es:\n\n<div style=\"text-align:center\">\n1, 2, 4, 2, 2, 2, 3, 2, 1, 1, 0, 2, 2, 0, 2, 2, 1, 2, 2, 3, 1, 2, 2, 1, 2\n</div>\n\nLa tabla de frecuencias del número de hijos en esta muestra es\n\n$$ \n\\begin{array}{rrrrr}\n\\hline\nx_i & n_i & f_i & N_i & F_i\\\\\n\\hline\n0 & 2 & 0.08 & 2 & 0.08\\\\\n1 & 6 & 0.24 & 8 & 0.32\\\\\n2 & 14 & 0.56 & 22 & 0.88\\\\\n3 & 2 & 0.08 & 24 & 0.96\\\\\n4 & 1 & 0.04 & 25 & 1 \\\\\n\\hline\n\\sum & 25 & 1 \\\\\n\\hline\n\\end{array}\n$$\n:::\n\n:::{#exm-tabla-frecuencias-datos-agrupados}\n## Variable cuantitativa y datos agrupados\nSe ha medido la estatura (en cm) de 30 universitarios obteniendo:\n\n<div style=\"text-align:center\">\n179, 173, 181, 170, 158, 174, 172, 166, 194, 185,<br>\n162, 187, 198, 177, 178, 165, 154, 188, 166, 171,<br>\n175, 182, 167, 169, 172, 186, 172, 176, 168, 187.\n</div>\n\nLa tabla de frecuencias de la estatura en a esta muestra es\n\n$$ \n\\begin{array}{crrrr}\n\\hline\nx_i & n_i & f_i & N_i & F_i\\\\\n\\hline\n(150,160] & 2 & 0.07 & 2 & 0.07\\\\\n(160,170] & 8 & 0.27 & 10 & 0.34\\\\\n(170,180] & 11 & 0.36 & 21 & 0.70\\\\\n(180,190] & 7 & 0.23 & 28 & 0.93\\\\\n(190,200] & 2 & 0.07 & 30 & 1 \\\\\n\\hline\n\\sum & 30 & 1 \\\\\n\\hline\n\\end{array}\n$$\n:::\n\n### Construcción de clases\n\nCada intervalo de agrupación de datos se denomina **clase** y el centro del intervalo se llama **marca de clase**.\n\nA la hora de agrupar los datos en clases hay que tener en cuenta lo siguiente:\n\n- El número de intervalos no debe ser muy grande ni muy pequeño. Una regla orientativa es tomar un número de intervalos próximo a $\\sqrt{n}$ o $\\log_2(n)$.\n- Los intervalos no deben solaparse y deben cubrir todo el rango de valores. Es indiferente si se abren por la izquierda y se cierran por la derecha o al revés.\n- El valor más pequeño debe caer dentro del primer intervalo y el más grande dentro del último.\n\n:::{#exm-tabla-frecuencias-cualitativa}\n## Variable cualitativa\nLos grupos sanguíneos de una muestra de 30 personas son:\n\n<div style=\"text-align:center\">\nA, B, B, A, AB, 0, 0, A, B, B, A, A, A, A, AB, A, A, A, B, 0, B, B, B, A, A, A, 0, A, AB, 0.\n</div>\n\nLa tabla de frecuencias del grupo sanguíneo en esta muestra es\n\n$$\n\\begin{array}{crr}\n\\hline\nx_i & n_i & f_i \\\\\n\\hline\n\\mbox{0} & 5 & 0.16 \\\\\n\\mbox{A} & 14 & 0.47 \\\\\n\\mbox{B} & 8 & 0.27 \\\\\n\\mbox{AB} & 3 & 0.10 \\\\\n\\hline\n\\sum & 30 & 1 \\\\\n\\hline\n\\end{array}\n$$\n:::\n\n:::{.callout-warning}\nObsérvese que en este caso las frecuencias acumuladas no tienen sentido al no existir un orden entre los valores de la variable.\n:::\n\n## Representaciones gráficas\n\nLa tabla de frecuencias también suele representarse gráficamente. Dependiendo del tipo de variable y de si se han agrupado o no los datos, se utilizan distintos tipos de gráficos:\n\n- Diagrama de barras\n\n- Histograma\n\n- Diagrama de líneas o polígonos.\n\n- Diagrama de sectores.\n\n### Diagrama de barras\n\nUn **diagrama de barras** consiste en un conjunto de barras, una para cada valor o categoría de la variable, dibujadas sobre unos ejes cartesianos.\n\nHabitualmente los valores o categorías de la variable se representan en eje $X$, y las frecuencias en el eje $Y$.\nPara cada valor o categoría se dibuja una barra con la altura correspondiente a su frecuencia. La anchura de la barra no es importante pero las barras deben aparecer claramente separadas unas de otras.\n\nDependiendo del tipo de frecuencia representada en el eje $Y$ se tienen diferentes tipos de diagramas de barras.\n\nEn ocasiones se dibuja un polígono, conocido como **polígono de frecuencias**, uniendo mediante segmentos los puntos más altos de cada barra.\n\n:::{#exm-diagrama-barras}\nEl diagrama de barras que aparece a continuación muestra la distribución de frecuencias absolutas del número de hijos en la muestra anterior.\n\n\n\n\n::: {.cell hash='02-estadistica-descriptiva_cache/epub/diagrama-barras_ed88673bf5dcbd1758bb787320d50b69'}\n::: {.cell-output-display}\n![](02-estadistica-descriptiva_files/figure-epub/diagrama-barras-1.png)\n:::\n:::\n\n\n\n\nY a continuación se muestra el polígono de frecuencias. \n\n\n\n\n::: {.cell hash='02-estadistica-descriptiva_cache/epub/poligono-frecuencias-absolutas_b23fcc6fafff7fa2bd9bf0dde3b3c942'}\n::: {.cell-output-display}\n![](02-estadistica-descriptiva_files/figure-epub/poligono-frecuencias-absolutas-1.png)\n:::\n:::\n\n\n\n\nEl diagrama de barras que aparece a continuación muestra la distribución de frecuencias relativas del número de hijos en la muestra anterior.\n\n\n\n\n::: {.cell hash='02-estadistica-descriptiva_cache/epub/diagrama-barras-relativas_59e339da43c5d5b9db0b9a2ebb0824f9'}\n::: {.cell-output-display}\n![](02-estadistica-descriptiva_files/figure-epub/diagrama-barras-relativas-1.png)\n:::\n:::\n\n\n\n\nEl diagrama de barras que aparece a continuación muestra la distribución de frecuencias absolutas acumuladas del número de hijos en la muestra anterior.\n\n\n\n\n::: {.cell hash='02-estadistica-descriptiva_cache/epub/diagrama-barras-acumuladas_bf11c08bbb176faff18a3afae40e0720'}\n::: {.cell-output-display}\n![](02-estadistica-descriptiva_files/figure-epub/diagrama-barras-acumuladas-1.png)\n:::\n:::\n\n\n\n\nY el diagrama de barras que aparece a continuación muestra la distribución de frecuencias relativas acumuladas del número de hijos en la muestra anterior.\n\n\n\n\n::: {.cell hash='02-estadistica-descriptiva_cache/epub/diagrama-barras-relativas-acumuladas_8070cf69c7619e1e64e9ae769c15a575'}\n::: {.cell-output-display}\n![](02-estadistica-descriptiva_files/figure-epub/diagrama-barras-relativas-acumuladas-1.png)\n:::\n:::\n\n\n\n\nFinalmente, el último diagrama muestra el polígono de frecuencias relativas acumuladas.\n\n\n\n\n::: {.cell hash='02-estadistica-descriptiva_cache/epub/poligono-relativas-acumuladas_ef1b6fd210f12c65250fd3181eda8fc8'}\n::: {.cell-output-display}\n![](02-estadistica-descriptiva_files/figure-epub/poligono-relativas-acumuladas-1.png)\n:::\n:::\n\n\n\n:::\n\n### Histograma\n\nUn _histograma_ es similar a un diagrama de barras pero para datos agrupados.\n\nHabitualmente las clases o intervalos de agrupación se representan en el eje $X$, y las frecuencias en el eje $Y$. Para cada clase se dibuja una barra de altura la correspondiente frecuencia. A diferencia del diagrama de barras, la anchura del la barra coincide con la anchura de las clases y no hay separación entre dos\nbarras consecutivas.\n\n:::{.content-visible when-format=\"html\"}\n![Clasifiación en clases.](img/descriptiva/histogram_creation.gif)\n:::\n\nDependiendo del tipo de frecuencia representada en el eje $Y$ existen distintos tipos de histogramas.\n\nAl igual que con el diagrama de barras, se puede dibujar un _polígono de frecuencias_ uniendo los puntos centrales más altos de cada barra con segmentos.\n\n:::{#exm-histograma}\nEl siguiente histograma muestra la distribución de frecuencias absolutas de las estaturas.\n\n\n\n\n::: {.cell hash='02-estadistica-descriptiva_cache/epub/histograma_46b914f274654f9febb31e8a0b29c05e'}\n::: {.cell-output-display}\n![](02-estadistica-descriptiva_files/figure-epub/histograma-1.png)\n:::\n:::\n\n\n\n\nEl siguiente histograma muestra la distribución de frecuencias relativas con el polígono de frecuencias.\n\n\n\n\n::: {.cell hash='02-estadistica-descriptiva_cache/epub/histograma-frecuencias-relativas_21af82e9c8f5cda4992a676f790046e0'}\n::: {.cell-output-display}\n![](02-estadistica-descriptiva_files/figure-epub/histograma-frecuencias-relativas-1.png)\n:::\n:::\n\n\n\n:::\n\nEl polígono de frecuencias acumuladas (absolutas o relativas) se conoce como **ojiva**.\n\n:::{#exm-ojiva}\nEl histograma y la ojiva siguientes muestran la distribución de frecuencias relativas acumuladas de estaturas.\n\n\n\n\n::: {.cell hash='02-estadistica-descriptiva_cache/epub/histograma-frecuencias-relativas-acumuladas_8a8b28d1ccaf9eff5ba0a37bb259d186'}\n::: {.cell-output-display}\n![](02-estadistica-descriptiva_files/figure-epub/histograma-frecuencias-relativas-acumuladas-1.png)\n:::\n:::\n\n\n\n:::\n\nObsérvese que en la ojiva se unen los vértices superiores derechos de cada barra con segmentos, en lugar de los puntos centrales, ya que no se consigue alcanzar la frecuencia acumulada correspondiente a la clase hasta que no se alcanza el final del intervalo.\n\n### Diagrama de sectores\n\nUn _diagrama de sectores_ consiste en un círculo divido en porciones, uno por cada valor o categoría de la variable.\nCada porción se conoce como _sector_ y su ángulo o área es proporcional a la correspondiente frecuencia del valor o categoría.\n\nLos diagramas de sectores pueden representar frecuencias absolutas o relativas, pero no pueden representar frecuencias acumuladas, y se utilizan sobre todo con atributos nominales.\nPara atributos ordinales o variables cuantitativas es mejor utilizar diagramas de barras, ya es más fácil percibir las diferencias en una dimensión (altura de las barras) que en dos dimensiones (áreas de los sectores).\n\n:::{#exm-diagrama-sectores}\nEl diagrama de sectores siguiente muestra la distribución de frecuencias relativas de los grupos sanguíneos.\n\n\n\n\n::: {.cell hash='02-estadistica-descriptiva_cache/epub/diagrama-sectores_613e74eb75b651748ebed0ca38c37b9c'}\n::: {.cell-output-display}\n![](02-estadistica-descriptiva_files/figure-epub/diagrama-sectores-1.png)\n:::\n:::\n\n\n\n:::\n\n### La distribución Normal\n\nLas distribuciones con diferentes propiedades presentan formas distintas.\n\n:::{#exm-distribucion-ingresos-familiares}\n## Distribución de los ingresos familiares\n\n\n\n\n::: {.cell hash='02-estadistica-descriptiva_cache/epub/histograma-ingresos-familiares_601bea13369d697105d0e8565e88d8d3'}\n::: {.cell-output-display}\n![](02-estadistica-descriptiva_files/figure-epub/histograma-ingresos-familiares-1.png)\n:::\n:::\n\n\n\n:::\n\n:::{#exm-distribucion-edad-fallecimiento}\n## Distribución de la edad de fallecimiento\n\n\n\n\n::: {.cell hash='02-estadistica-descriptiva_cache/epub/histograma-edad-fallecimiento_b7832a313c6a87bf21f85ea10a3ac3eb'}\n::: {.cell-output-display}\n![](02-estadistica-descriptiva_files/figure-epub/histograma-edad-fallecimiento-1.png)\n:::\n:::\n\n\n\n:::\n\n:::{#exm-distribucion-tiempo-espera-metro}\n## Distribución del tiempo de espera del metro\n\n\n\n\n::: {.cell hash='02-estadistica-descriptiva_cache/epub/histograma-tiempo-espera-metro_f66099f83a51a3efdb4fd80e660eacb3'}\n::: {.cell-output-display}\n![](02-estadistica-descriptiva_files/figure-epub/histograma-tiempo-espera-metro-1.png)\n:::\n:::\n\n\n\n:::\n\n:::{#exm-distribucion-llegada-clientes-restaurantes}\n## Distribución del tiempo de llegada de clientes a un restaurante\n\n\n\n\n::: {.cell hash='02-estadistica-descriptiva_cache/epub/histograma-tiempo-llegada-restaurante_bbc0a27c964a53e64ae3685ec2ed2052'}\n::: {.cell-output-display}\n![](02-estadistica-descriptiva_files/figure-epub/histograma-tiempo-llegada-restaurante-1.png)\n:::\n:::\n\n\n\n:::\n\nLas distribuciones con forma de campana se presentan muy a menudo en las variables biológicas.\n\n:::{#exm-distribucion-peso-hombres}\n## Distribución del peso de los hombres\n\n\n\n\n::: {.cell hash='02-estadistica-descriptiva_cache/epub/histograma-peso-hombres_4150ec9b5a922f4e1a91e3309cfd96b1'}\n::: {.cell-output-display}\n![](02-estadistica-descriptiva_files/figure-epub/histograma-peso-hombres-1.png)\n:::\n:::\n\n\n\n:::\n\n:::{#exm-distribucion-estatura-mujeres}\n## Distribución de la estatura de las mujeres\n\n\n\n\n::: {.cell hash='02-estadistica-descriptiva_cache/epub/histograma-estatura-mujeres_23490f703c8f2246079f79627acbfece'}\n::: {.cell-output-display}\n![](02-estadistica-descriptiva_files/figure-epub/histograma-estatura-mujeres-1.png)\n:::\n:::\n\n\n\n:::\n\n:::{#exm-distribucion-estaturas-sexo}\n## Distribución de la estatura según el sexo\n\n\n\n\n::: {.cell hash='02-estadistica-descriptiva_cache/epub/histograma-estatura-sexo_8a8434c8928087efc03980458d1770cb'}\n::: {.cell-output-display}\n![](02-estadistica-descriptiva_files/figure-epub/histograma-estatura-sexo-1.png)\n:::\n:::\n\n\n\n:::\n\n:::{#exm-distribucion-estaturas-ambos-sexos}\n## Distribución de la estatura de hombres y mujeres\n\n\n\n\n::: {.cell hash='02-estadistica-descriptiva_cache/epub/histograma-estatura-ambos-sexo_7cc2c93847490a57b23d766bcd2b87a2'}\n::: {.cell-output-display}\n![](02-estadistica-descriptiva_files/figure-epub/histograma-estatura-ambos-sexo-1.png)\n:::\n:::\n\n\n\n:::\n\n:::{#exm-distribucion-colesterol}\n## Distribución del colesterol\n\n\n\n\n::: {.cell hash='02-estadistica-descriptiva_cache/epub/histograma-colesterol_da52c23dbaa9ec8b11a203911b521768'}\n::: {.cell-output-display}\n![](02-estadistica-descriptiva_files/figure-epub/histograma-colesterol-1.png)\n:::\n:::\n\n\n\n:::\n\n:::{#exm-distribucion-notas}\n## Distribución de notas\n\n\n\n\n::: {.cell hash='02-estadistica-descriptiva_cache/epub/histograma-notas_97607c1a16ad94722bbaf0c1596ce11f'}\n::: {.cell-output-display}\n![](02-estadistica-descriptiva_files/figure-epub/histograma-notas-1.png)\n:::\n:::\n\n\n\n:::\n\nLa distribución con forma de campana aparece tan a menudo en la Naturaleza que se conoce como _distribución normal_ o _distribución gaussiana_.\n\n:::{.content-visible when-format=\"html\"}\n![Campana de Gauss.](img/descriptiva/campana-gauss.png)\n:::\n\n:::{.content-visible unless-format=\"html\"}\n![Campana de Gauss.](img/descriptiva/campana-gauss.tex)\n:::\n\n\n## Datos atípicos\n\nUno de los principales problemas de las muestras son los **datos atípicos**, que son valores de la variable que se diferencian mucho del resto de los valores en la muestra.\n\n![Dato atípico.](img/descriptiva/dato_atipico.png)\n\nEs muy importante detectar los datos atípicos antes de realizar cualquier análisis de los datos, pues suelen distorsionar los resultados.\n\nAparecen siempre en los extremos de la distribución, y pueden detectarse con un diagrama de caja y bigotes (tal y como veremos más adelante).\n\n### Tratamiento de los datos atípicos\n\nCuando trabajemos con muestras grandes, los datos atípicos tienen menor influencia y pueden dejarse en la muestra.\n\nCuando trabajemos con muestras pequeñas tenemos varias opciones:\n\n- Eliminar el dato atípico si se trata de un error.\n- Sustituir el dato atípico por el menor o el mayor valor de la distribución que no es atípico si no se trata de un error y el dato atípico no concuerda con la distribución teórica.\n- Dejar el dato atípico si no es un error, y cambiar el modelo de distribución teórico para adecuarlo a los datos atípicos.\n\n## Estadísticos muestrales\n\nLa tabla de frecuencias sintetiza la información de la distribución de valores de la variable estudiada en la muestra, pero en muchas ocasiones es insuficiente para describir determinados aspectos de la distribución, como por ejemplo, cuáles son los valores más representativos de la muestra, cómo es la variabilidad de los datos, qué datos pueden considerarse atípicos, o cómo es la simetría de la distribución.\n\nPara describir esos aspectos de la distribución muestral se utilizan unas medidas resumen llamadas **estadísticos muestrales**.\n\nDe acuerdo al aspecto de las distribución que miden, existen diferentes tipos de estadísticos:\n\n**Estadísticos de Posición**: Miden los valores en torno a los que se agrupan los datos o que dividen la distribución en partes iguales.\n\n**Estadísticos de Dispersión**: Miden la heterogeneidad de los datos.\n\n**Estadísticos de Forma**: Miden aspectos de la forma que tiene la distribución de los datos, como la simetría o el apuntamiento.\n\n## Estadísticos de posición\n\nPueden ser de dos tipos:\n\n**Estadísticos de Tendencia Central**: Determinan valores alrededor de los cuales se concentran los datos, habitualmente en el centro de la distribución. Estas medidas suelen utilizarse como valores representativos de la muestra. Las más importantes son:\n\n- Media aritmética\n- Mediana\n- Moda\n\n**Estadísticos de Posición no centrales**: Dividen la distribución en partes con el mismo número de datos. Las más importantes son:\n\n- Cuartiles.\n- Deciles.\n- Percentiles.\n\n### Media aritmética\n\n:::{#def-media-aritmetica}\n## Media aritmética muestral $\\bar{x}$\nLa _media aritmética muestral_ de una variable $X$ es la suma de los valores observados en la muestra dividida por el tamaño muestral\n\n$$\\bar{x} = \\frac{\\sum x_i}{n}$$\n:::\n\nA partir de la tabla de frecuencias puede calcularse con la fórmula\n\n$$\\bar{x} = \\frac{\\sum x_in_i}{n} = \\sum x_i f_i$$\n\nEn la mayoría de los casos, la media aritmética es la medida que mejor representa a la muestra.\n\n:::{.callout-warning}\nNo puede calcularse para variables cualitativas.\n:::\n\n:::{#exm-media-datos-no-agrupados}\n## Datos no agrupados\nUtilizando los datos de la muestra del número de hijos en las familias, la media aritmética es\n\n\\begin{align*}\n\\bar{x} &= \\frac{1+2+4+2+2+2+3+2+1+1+0+2+2}{25}+\\\\\n &+\\frac{0+2+2+1+2+2+3+1+2+2+1+2}{25} = \\frac{44}{25} = 1.76 \\mbox{ hijos}.\n\\end{align*}\n\no bien, desde la tabla de frecuencias\n\n$$\n\\begin{array}{rrrrr}\n\\hline\nx_i & n_i & f_i & x_in_i & x_if_i\\\\\n\\hline\n0 & 2 & 0.08 & 0 & 0\\\\\n1 & 6 & 0.24 & 6 & 0.24\\\\\n2 & 14 & 0.56 & 28 & 1.12\\\\\n3 & 2  & 0.08 & 6 & 0.24\\\\\n4 & 1 & 0.04 & 4 & 0.16 \\\\\n\\hline\n\\sum & 25 & 1 & 44 & 1.76 \\\\\n\\hline\n\\end{array}\n$$\n\n$$\n\\bar{x} = \\frac{\\sum x_in_i}{n} = \\frac{44}{25}= 1.76 \\mbox{ hijos}\\qquad \\bar{x}=\\sum{x_if_i} = 1.76 \\mbox{ hijos}.\n$$\n\nEsto significa que el valor que mejor representa el número de hijos en las familias de la muestra es 1.76 hijos.\n:::\n\n:::{#exm-media-datos-agrupados}\n## Datos agrupados\nUtilizando los datos de la muestra de estaturas, la media es\n\n$$\n\\bar{x} = \\frac{179+173+\\cdots+187}{30} = 175.07 \\mbox{ cm}.\n$$\n\no bien, desde la tabla de frecuencias utilizando las marcas de clase $x_i$:\n\n$$\n\\begin{array}{crrrrr}\n\\hline\nX & x_i & n_i & f_i & x_in_i & x_if_i\\\\\n\\hline\n(150,160] & 155 & 2 & 0.07 & 310 & 10.33\\\\\n(160,170] & 165 & 8 & 0.27 & 1320 & 44.00\\\\\n(170,180] & 175 & 11 & 0.36 & 1925 & 64.17\\\\\n(180,190] & 185 & 7 & 0.23 & 1295 & 43.17\\\\\n(190,200] & 195 & 2 & 0.07 & 390 & 13 \\\\\n\\hline\n\\sum &  & 30 & 1 & 5240 & 174.67 \\\\\n\\hline\n\\end{array}\n$$\n\n$$\n\\bar{x} = \\frac{\\sum x_in_i}{n} = \\frac{5240}{30}= 174.67 \\mbox{ cm} \\qquad \\bar{x}=\\sum{x_if_i} = 174.67 \\mbox{ cm}.\n$$\n\nObsérvese que al calcular la media desde la tabla de frecuencias el resultado difiere ligeramente del valor real obtenido directamente desde la muestra, ya que los valores usados en los cálculos no son los datos reales sino las marcas de clase.\n:::\n\n#### Media ponderada\n\nEn algunos casos, los valores de la muestra no tienen la misma importancia. En este caso la importancia o _peso_ de cada valor de la muestra debe tenerse en cuenta al calcular la media.\n\n:::{#def-media-ponderada}\n## Media ponderada muestral $\\bar x_p$\nDada una muestra de valores $x_1,\\ldots, x_n$ donde cada valor $x_i$ tiene asociado un peso $p_i$, la _media ponderada muestral_ de la variable $X$ es la suma de los productos de cada valor observado en la muestra por su peso, dividida por la suma de todos los pesos\n\n$$\\bar{x}_p = \\frac{\\sum x_ip_i}{\\sum p_i}$$\n:::\n\nA partir de la tabla de frecuencias puede calcularse con la fórmula\n\n$$\\bar{x}_p = \\frac{\\sum x_ip_in_i}{\\sum p_i}$$\n\n:::{#exm-media-ponderada}\nSupóngase que un estudiante quiere calcular una medida que represente su rendimiento en el curso. La nota obtenida en cada asignatura y sus créditos son\n\n| Asignatura  | Créditos | Nota |\n| :---------: | :------: | :--- |\n| Matemáticas |    6     | 5    |\n|  Economía   |    4     | 3    |\n|   Química   |    8     | 6    |\n\nLa media aritmética vale\n\n$$\\bar{x} = \\frac{\\sum x_i}{n} = \\frac{5+3+6}{3}= 4.67 \\text{ puntos}.$$\n\nSin embargo, esta nota no representa bien el rendimiento académico del alumno ya que no todas las asignaturas tienen la misma importancia ni requieren el mismo esfuerzo para aprobar. Las asignaturas con más créditos requieren más trabajo y deben tener más peso en el cálculo de la media.\n\nEs más lógico usar la media ponderada como medida del rendimiento del estudiante, tomando como pesos los créditos de cada asignatura\n\n$$\n\\bar{x}_p = \\frac{\\sum x_ip_i}{\\sum p_i} = \\frac{5\\cdot 6+3\\cdot 4+6\\cdot 8}{6+4+8}= \\frac{90}{18} = 5 \\text{ puntos}.\n$$\n:::\n\n### Mediana\n\n:::{#def-mediana}\n## Mediana muestral $Me$\nLa _mediana muestral_ de una variable $X$ es el valor de la variable que está en el medio de la muestra ordenada.\n:::\n\nLa mediana divide la distribución de la muestra en dos partes iguales, es decir, hay el mismo número de valores por debajo y por encima de la mediana. Por tanto, tiene frecuencias acumuladas $N_{Me}= n/2$ y $F_{Me}= 0.5$.\n\n:::{.callout-warning}\nNo puede calcularse para variables nominales.\n:::\n\nCon datos no agrupados pueden darse varios casos:\n\n- Tamaño muestral impar: La mediana es el valor que ocupa la posición $\\frac{n+1}{2}$.\n- Tamaño muestral par: La mediana es la media de los valores que ocupan las posiciones $\\frac{n}{2}$ y $\\frac{n}{2}+1$.\n\n:::{.content-visible when-format=\"html\"}\n![Cálculo de la mediana con datos no agrupados.](img/descriptiva/mediana.svg)\n:::\n\n:::{.content-visible unless-format=\"html\"}\n![Cálculo de la mediana con datos no agrupados.](img/descriptiva/mediana.png)\n:::\n\n:::{#exm-mediana-datos-no-agrupados}\nUtilizando los datos del número de hijos de las familias, el tamaño muestral es 25, que es impar, y la mediana es el valor que ocupa la posición $\\frac{25+1}{2} = 13$ de la muestra ordenada.\n\n$$\n0,0,1,1,1,1,1,1,2,2,2,2,\\fbox{2},2,2,2,2,2,2,2,2,2,3,3,4\n$$\n\ny la mediana es 2 hijos.\n\nSi se trabaja con la tabla de frecuencias, la mediana es el valor más pequeño con una frecuencia acumulada mayor o igual a $13$, o con una frecuencia relativa acumulada mayor o igual que $0.5$.\n\n$$\n\\begin{array}{rrrrr}\n\\hline\nx_i & n_i & f_i & N_i & F_i\\\\\n\\hline\n0 & 2 & 0.08 & 2 & 0.08\\\\\n1 & 6 & 0.24 & 8 & 0.32\\\\\n\\color{red}2 & 14 & 0.56 & 22 & 0.88\\\\\n3 & 2  & 0.08 & 24 & 0.96\\\\\n4 & 1 & 0.04 & 25 & 1 \\\\\n\\hline\n\\sum & 25 & 1 \\\\\n\\hline\n\\end{array}\n$$\n\n#### Cálculo de la mediana con datos agrupados\n\nCon datos agrupados la mediana se calcula interpolando en el polígono de frecuencias relativas acumuladas para el valor 0.5.\n\n:::{.content-visible when-format=\"html\"}\n![Cálculo de la mediana con datos agrupados.](img/descriptiva/interpolacion.svg)\n:::\n\n:::{.content-visible unless-format=\"html\"}\n![Cálculo de la mediana con datos agrupados.](img/descriptiva/interpolacion.png)\n:::\n\nAmbas expresiones son iguales ya que el ángulo $\\alpha$ es el mismo, y resolviendo la ecuación se tiene la siguiente fórmula para calcular la mediana\n\n$$\nMe=l_i+\\frac{0.5-F_{i-1}}{F_i-F_{i-1}}(l_i-l_{i-1})=l_i+\\frac{0.5-F_{i-1}}{f_i}a_i\n$$\n\n:::{#exm-mediana-datos-agrupados}\n## Datos agrupados\nUtilizando los datos de la muestra de las estaturas de estudiantes, la mediana cae en la clase (170,180].\n\n:::{.content-visible when-format=\"html\"}\n![Ejemplo de cálculo de la mediana con datos agrupados.](img/descriptiva/interpolacion_ejemplo_1.svg)\n:::\n\n:::{.content-visible unless-format=\"html\"}\n![Ejemplo de cálculo de la mediana con datos agrupados.](img/descriptiva/interpolacion_ejemplo_1.png)\n:::\n\nInterpolando en el intervalo (170,180] se tiene\n\n:::{.content-visible when-format=\"html\"}\n![Ejemplo de cálculo de la mediana con datos agrupados.](img/descriptiva/interpolacion_ejemplo_2.svg)\n:::\n\n:::{.content-visible unless-format=\"html\"}\n![Ejemplo de cálculo de la mediana con datos agrupados.](img/descriptiva/interpolacion_ejemplo_2.png)\n:::\n\nIgualando ambas expresiones y resolviendo la ecuación se obtiene\n\n$$\nMe= 170+\\frac{0.5-0.34}{0.7-0.34}(180-170)=170+\\frac{0.16}{0.36}10=174.54 \\mbox{ cm}.\n$$\n\nEsto significa que la mitad de los estudiantes tienen estaturas menores o iguales que 174.54 cm y la otra mitad mayores o iguales.\n:::\n\n### Moda\n\n:::{#def-moda}\n## Moda muestral $Mo$\nLa _moda muestral_ de una variable $X$ es el valor de la variable más frecuente en la muestra.\n:::\n\nCon datos agrupados la _clase modal_ es la clase con mayor frecuencia en la muestra.\n\nPuede calcularse para todos los tipos de variables (cuantitativas y cualitativas).\n\nLas distribuciones pueden tener más de una moda.\n\n![Cálculo de la moda.](img/descriptiva/moda.png)\n\n:::{#exm-moda-datos-no-agrupados}\nUtilizando los datos de la muestra del número de hijos en las familias, el valor con mayor frecuencia es 2, y por tanto la moda es $Mo=2$.\n\n$$\n\\begin{array}{rr}\n\\hline\nx_i & n_i \\\\\n\\hline\n0 & 2 \\\\\n1 & 6 \\\\\n\\color{red} 2 & 14 \\\\\n3 & 2  \\\\\n4 & 1 \\\\\n\\hline\n\\end{array}\n$$\n:::\n\n:::{#exm-moda-datos-agrupados}\nUtilizando los datos de la muestra de estaturas de estudiantes, la clase con la mayor frecuencia es $(170,180]$, que es la clase modal $Mo=(170,180]$.\n\n$$\n\\begin{array}{cr}\n\\hline\nX & n_i \\\\\n\\hline\n(150,160] & 2 \\\\\n(160,170] & 8 \\\\\n\\color{red}{(170,180]} & 11 \\\\\n(180,190] & 7 \\\\\n(190,200] & 2 \\\\\n\\hline\n\\end{array}\n$$\n:::\n\n### ¿Qué estadístico de tendencia central usar?\n\nEn general, siempre que puedan calcularse los estadísticos de tendencia central, es recomendable utilizarlos como valores representativos en el siguiente orden:\n\n1. Media. La media utiliza más información que el resto ya que para calcularla se tiene en cuenta la magnitud de los datos.\n\n2. Mediana. La mediana utiliza menos información que la media, pero más que la moda, ya que para calcularla se tiene en cuenta el orden de los datos.\n\n3. Moda. La moda es la que menos información utiliza ya que para calcularla sólo se tienen en cuenta las frecuencias absolutas.\n\n:::{.callout-warning}\nHay que tener cuidado con los datos atípicos, ya que la media puede distorsionarse cuando hay datos atípicos. En tal caso es mejor utilizar la mediana como valor más representativo.\n:::\n\n:::{#exm-media-mediana-datos-atipicos}\nSi una muestra de número de hijos de 7 familias es\n\n<div style=\"text-align:center\">\n0, 0, 1, 1, 2, 2, 15,\n</div>\n\nentonces, $\\bar{x}=3$ hijos y $Me=1$ hijo.\n\n_¿Qué medida representa mejor el número de hijos en la muestra?_\n:::\n\n### Medidas de posición no centrales\n\nLas medidas de posición no centrales o _cuantiles_ dividen la distribución en partes iguales.\n\nLos más utilizados son:\n\n**Cuartiles**: Dividen la distribución en 4 partes iguales. Hay 3 cuartiles: $C_1$ (25% acumulado), $C_2$ (50% acumulado), $C_3$ (75% acumulado).\n\n**Deciles**: Dividen la distribución en 10 partes iguales. Hay 9 deciles: $D_1$ (10% acumulado),..., $D_9$ (90% acumulado).\n\n**Percentiles**: Dividen la distribución en 100 partes iguales. Hay 99 percentiles: $P_1$ (1% acumulado),..., $P_{99}$ (99% acumulado).\n\n:::{.content-visible when-format=\"html\"}\n![Cuartiles, deciles y percentiles.](img/descriptiva/cuantiles.svg)\n:::\n\n:::{.content-visible unless-format=\"html\"}\n![Cuartiles, deciles y percentiles.](img/descriptiva/cuantiles.png)\n:::\n\nObsérvese que hay una correspondencia entre los cuartiles, los deciles y los percentiles. Por ejemplo, el primer cuartil coincide con el percentil 25, y el cuarto decil coincide con el percentil 40.\n\nLos cuantiles se calculan de forma similar a la mediana. La única diferencia es la frecuencia relativa acumulada que corresponde a cada cuantil.\n\n:::{.content-visible when-format=\"html\"}\n![Cálculo de cuartiles, deciles y percentiles.](img/descriptiva/cuantiles_calculo.svg)\n:::\n\n:::{.content-visible unless-format=\"html\"}\n![Cálculo de cuartiles, deciles y percentiles.](img/descriptiva/cuantiles_calculo.png)\n:::\n\n:::{#exm-cuantiles-datos-no-agrupados}\nUtilizando los datos de la muestra del número de hijos de las familias, la frecuencia relativa acumulada era\n\n$$\n\\begin{array}{rr}\n\\hline\nx_i & F_i \\\\\n\\hline\n0 & 0.08\\\\\n1 & 0.32\\\\\n2 & 0.88\\\\\n3 & 0.96\\\\\n4 & 1\\\\\n\\hline\n\\end{array}\n$$\n\n\\begin{align*}\nF_{C_1}=0.25 &\\Rightarrow Q_1 = 1 \\text{ hijos},\\\\\nF_{C_2}=0.5 &\\Rightarrow Q_2 = 2 \\text{ hijos},\\\\\nF_{C_3}=0.75 &\\Rightarrow Q_3 = 2 \\text{ hijos},\\\\\nF_{D_4}=0.4 &\\Rightarrow D_4 = 2 \\text{ hijos},\\\\\nF_{P_{92}}=0.92 &\\Rightarrow P_{92} = 3 \\text{ hijos}.\n\\end{align*}\n:::\n\n## Estadísticos de dispersión\n\nLa _dispersión_ se refiere a la heterogeneidad o variabilidad de los datos. Así pues, los estadísticos de dispersión mide la variabilidad global de los datos, o con respecto a una medida de tendencia central.\n\nPara las variables cuantitativas, las más empleadas son:\n\n- Recorrido.\n- Rango Intercuartílico.\n- Varianza.\n- Desviación Típica.\n- Coeficiente de Variación.\n\n### Recorrido\n\n:::{#def-recorrido-muestral}\n## Recorrido muestral $Re$\nEl _recorrido muestral_ o _rango muestral_ de una variable $X$ se define como la diferencia entre el máximo y el mínimo de los valores en la muestra.\n\n$$Re = \\max_{x_i} -\\min_{x_i}$$\n:::\n\n:::{.content-visible when-format=\"html\"}\n![Rango muestral.](img/descriptiva/rango.svg)\n:::\n\n:::{.content-visible unless-format=\"html\"}\n![Rango muestral.](img/descriptiva/rango.png)\n:::\n\nEl recorrido mide la máxima variación que hay entre los datos muestrales. No obstante, es muy sensible a datos atípicos ya que suelen aparecer justo en los extremos de la distribución, por lo que no se suele utilizar mucho.\n\n### Rango intercuartílico\n\nPara evitar el problema de los datos atípicos en el recorrido, se puede utilizar el primer y tercer cuartil en lugar del mínimo y el máximo.\n\n:::{#def-rango-intercuartilico}\n## Rango intercuartílico muestral $RI$\nEl _rango intercuartílico muestral_ de una variable $X$ se define como la diferencia entre el tercer y el primer cuartil de la muestra.\n\n$$RI = C_3 -C_1$$\n:::\n\n:::{.content-visible when-format=\"html\"}\n![Rango intercuartílico.](img/descriptiva/rango_intercuartilico.svg)\n:::\n\n:::{.content-visible unless-format=\"html\"}\n![Rango intercuartílico.](img/descriptiva/rango_intercuartilico.png)\n:::\n\nEl rango intercuartílico mide la dispersión del 50% de los datos centrales.\n\n### Diagrama de caja y bigotes\n\nLa dispersión de una variable suele representarse gráficamente mediante un _diagrama de caja y bigotes_, que representa cinco estadísticos descriptivos (mínimo, cuartiles y máximo) conocidos como los _cinco números_. Consiste en una caja, dibujada desde el primer al tercer cuartil, que representa el rango intercuartílico, y dos segmentos, conocidos como _bigotes_ inferior y superior. A menudo la caja se divide en dos por la mediana.  \n\nEste diagrama es muy útil y se utiliza para muchos propósitos:\n\n- Sirve para medir la dispersión de los datos ya que representa el rango y el rango intercuartílico.\n- Sirve para detectar datos atípicos, que son los valores que quedan fuera del intervalo definido por los bigotes.\n- Sirve para medir la simetría de la distribución, comparando la longitud de las cajas y de los bigotes por encima y por debajo de la mediana.\n\n:::{#exm-diagrama-caja}\nEl diagrama siguiente muestra el diagrama de caja y bigotes del peso de una muestra de recién nacidos.\n\n:::{.content-visible when-format=\"html\"}\n![Diagrama de caja y bigotes del peso de recién nacidos.](img/descriptiva/diagrama_caja.svg)\n:::\n\n:::{.content-visible unless-format=\"html\"}\n![Diagrama de caja y bigotes del peso de recién nacidos.](img/descriptiva/diagrama_caja.png)\n:::\n\nPara construir el diagrama de caja y bigotes hay que seguir los siguientes pasos:\n\n1. Calcular los cuartiles.\n2. Dibujar una caja de manera que el extremo inferior caiga sobre el primer cuartil y el extremo superior sobre el tercer cuartil.\n3. Dividir la caja con una línea que caiga sobre el segundo cuartil.\n4. Para los bigotes inicialmente se calculan dos valores llamados _vallas_ $v_1$ y $v_2$. La valla inferior es el primer cuartil menos una vez y media el rango intercuartílico, y la valla superior es el tercer cuartil más una vez y media el rango intercuartílico.\n\n    $$\n    \\begin{aligned}\n    v_1&=Q_1-1.5\\,\\text{IQR}\\\\\n    v_2&=Q_3+1.5\\,\\text{IQR}\n    \\end{aligned}\n    $$\n\n    Las vallas definen el intervalo donde los datos se consideran normales. Cualquier valor fuera de ese intervalo se considera un dato atípico.  \n    El bigote superior se dibuja desde el borde inferior de la caja hasta el menor valor de la muestra que es mayor o igual a la valla inferior, y el bigote superior se dibuja desde el borde superior de la caja hasta el mayor valor de la muestra que es menor o igual a la valla superior.\n\n:::{.callout-warning}\nLos bigotes no son las vallas.\n:::\n\n5. Finalmente, si en la muestra hay algún dato atípico, se dibuja un punto para cada uno de ellos.\n\n:::{#exm-diagrama-caja}\nEl diagrama de caja y bigotes de la muestra del número de hijos de las familias se muestra a continuación.\n\n:::{.content-visible when-format=\"html\"}\n![Diagrama de caja y bigotes del número de hijos.](img/descriptiva/diagrama_caja_hijos.svg)\n:::\n\n:::{.content-visible unless-format=\"html\"}\n![Diagrama de caja y bigotes del número de hijos.](img/descriptiva/diagrama_caja_hijos.png)\n:::\n:::\n\n#### Desviaciones respecto de la media\n\nOtra forma de medir la variabilidad de una variable es estudiar la concentración de los valores en torno a algún estadístico de tendencia central como por ejemplo la media.\n\nPara ello se suele medir la distancia de cada valor a la media. A ese valor se le llama **desviación de la media**.\n\n:::{.content-visible when-format=\"html\"}\n![Desviaciones con respecto a la media.](img/descriptiva/desviaciones.svg)\n:::\n\n:::{.content-visible unless-format=\"html\"}\n![Desviaciones con respecto a la media.](img/descriptiva/desviaciones.png)\n:::\n\nSi las desviaciones son grandes la media no será tan representativa como cuando la desviaciones sean pequeñas.\n\n:::{#exm-desviaciones}\nLa siguiente tabla contiene las notas de 3 estudiantes en un curso con las asignaturas $A$, $B$ y $C$.\n\n$$\n\\begin{array}{cccc}\n\\hline\nA & B & C & \\bar x \\\\\n0 & 5 & 10 & 5 \\\\\n4 & 5 & 6 & 5 \\\\\n5 & 5 & 5 & 5 \\\\\n\\hline\n\\end{array}\n$$\n\nTodos los estudiantes tienen la misma media, pero, en qué caso la media representa mejor el rendimiento en el curso?\n:::\n\n### Varianza y desviación típica\n\n:::{#def-varianza}\n## Varianza $s^2$\nLa _varianza muestral_ de una variable $X$ se define como el promedio del cuadrado de las desviaciones de los valores de la muestra respecto de la media muestral.\n\n$$s^2 = \\frac{\\sum (x_i-\\bar x)^2n_i}{n} = \\sum (x_i-\\bar x)^2f_i$$\n:::\n\nTambién puede calcularse de manera más sencilla mediante la fórmula\n\n$$s^2 = \\frac{\\sum x_i^2n_i}{n} -\\bar x^2= \\sum x_i^2f_i-\\bar x^2$$\n\nLa varianza tiene las unidades de la variable al cuadrado, por lo que para facilitar su interpretación se suele utilizar su raíz cuadrada.\n\n:::{#def-desviacion-tipica}\n## Desviación típica $s$\nLa _desviación típica muestral_ de una variable $X$ se define como la raíz cuadrada positiva de su varianza muestral.\n\n$$s = +\\sqrt{s^2}$$\n:::\n\n:::{.callout-tip}\nTanto la varianza como la desviación típica sirven para cuantificar la dispersión de los datos en torno a la media. Cuando la varianza o la desviación típica son pequeñas, los datos de la muestra están concentrados en torno a la media, y la media es una buena medida de representatividad. Por contra, cuando la varianza o la desviación típica son grandes, los datos de la muestra están alejados de la media, y la media ya no representa tan bien.\n\n|                           |               |                         |\n| :------------------------ | :-----------: | :---------------------- |\n| Desviación típica pequeña | $\\Rightarrow$ | Media representativa    |\n| Desviación típica grande  | $\\Rightarrow$ | Media no representativa |\n:::\n\n:::{#exm-intrepretacion-desviacion-tipica}\nLas siguientes muestras contienen las notas de dos estudiantes en dos asignaturas.\n\n:::{.content-visible when-format=\"html\"}\n![Interpretación de la desviación típica.](img/descriptiva/interpretacion_desviacion_tipica.svg)\n:::\n\n:::{.content-visible unless-format=\"html\"}\n![Interpretación de la desviación típica.](img/descriptiva/interpretacion_desviacion_tipica.png)\n:::\n\n_¿Qué media es más representativa?_\n:::\n\n:::{#exm-desviacion-tipica-datos-no-agrupados}\n## Datos no agrupados\nUtilizando los datos de la muestra del número de hijos de las familias, con una media $\\bar x=1.76$ hijos, y añadiendo una nueva columna a la tabla de frecuencias con los cuadrados de los valores,\n\n$$\n\\begin{array}{rrr}\n\\hline\nx_i & n_i & x_i^2n_i \\\\\n\\hline\n0 & 2 & 0 \\\\\n1 & 6 & 6 \\\\\n2 & 14 & 56\\\\\n3 & 2  & 18\\\\\n4 & 1 & 16 \\\\\n\\hline\n\\sum & 25 & 96 \\\\\n\\hline\n\\end{array}$$\n\n$$s^2 = \\frac{\\sum x_i^2n_i}{n}-\\bar x^2 = \\frac{96}{25}-1.76^2= 0.7424 \\mbox{ hijos}^2.$$\n\ny la desviación típica es $s=\\sqrt{0.7424} = 0.8616$ hijos.\n\nComparado este valor con el recorrido, que va de 0 a 4 hijos se observa que no es demasiado grande por lo que se puede concluir que no hay mucha dispersión y en consecuencia la media de $1.76$ hijos representa bien el número de hijos de las familias de la muestra.\n:::\n\n:::{#exm-desviacion-tipica-datos-agrupados}\n## Datos agrupados\nUtilizando los datos de la muestra de estaturas de los estudiantes y agrupando las estaturas en clases, se obtenía una media $\\bar x = 174.67$ cm. El cálculo de la varianza se realiza igual que antes pero tomando como valores de la variable las marcas de clase.\n\n$$\n\\begin{array}{crrr}\n\\hline\nX & x_i & n_i & x_i^2n_i \\\\\n\\hline\n(150,160] & 155 & 2 & 48050\\\\\n(160,170] & 165 & 8 & 217800\\\\\n(170,180] & 175 & 11 & 336875\\\\\n(180,190] & 185 & 7 & 239575\\\\\n(190,200] & 195 & 2 & 76050\\\\\n\\hline\n\\sum &  & 30 & 918350 \\\\\n\\hline\n\\end{array}\n$$\n\n$$s^2 = \\frac{\\sum x_i^2n_i}{n}-\\bar x^2 = \\frac{918350}{30}-174.67^2= 102.06 \\mbox{ cm}^2,$$\n\ny la desviación típica es $s=\\sqrt{102.06} = 10.1$ cm.\n\nEste valor es bastante pequeño, comparado con el recorrido de la variable, que va de 150 a 200 cm, por lo que la variable tiene poca dispersión y en consecuencia su media es muy representativa.\n:::\n\n### Coeficiente de variación\n\nTanto la varianza como la desviación típica tienen unidades y eso dificulta a veces su interpretación, especialmente cuando se compara la dispersión de variables con diferentes unidades.\n\nPor este motivo, es también común utilizar la siguiente medida de dispersión que no tiene unidades.\n\n:::{#def-coeficiente-variacion}\n## Coeficiente de variación muestral $cv$\nEl _coeficiente de variación muestral_ de una variable $X$ se define como el cociente entre su desviación típica muestral y el valor absoluto de su media muestral.\n\n$$cv = \\frac{s}{|\\bar x|}$$\n:::\n\n:::{.callout-tip}\nEl coeficiente de variación muestral mide la dispersión relativa de los valores de la muestra en torno a la media muestral.\n\nComo no tiene unidades, es muy sencillo de interpretar: Cuanto mayor sea, mayor será la dispersión relativa con respecto a la media y menos representativa será la media.\n:::\n\nEl coeficiente de variación es muy útil para comparar la dispersión de distribuciones de variables diferentes, incluso si las variables tienen unidades diferentes.\n\n:::{#exm-coeficiente-variacion}\nEn la muestra del número de hijos, donde la media era $\\bar x=1.76$ hijos y la desviación típica $s=0.8616$ hijos, el coeficiente de variación vale\n\n$$cv = \\frac{s}{|\\bar x|} = \\frac{0.8616}{|1.76|} = 0.49.$$\n\nEn la muestra de las estaturas, donde la media era $\\bar x=174.67$ cm y la desviación típica $s=10.1$ cm, el coeficiente de variación vale\n\n$$cv = \\frac{s}{|\\bar x|} = \\frac{10.1}{|174.67|} = 0.06.$$\n\nEsto significa que la dispersión relativa en la muestra de estaturas es mucho menor que en la del número de hijos, por lo que la media de las estaturas será más representativa que la media del número de hijos.\n:::\n\n## Estadísticos de forma\n\nSon medidas que describen la forma de la distribución.\n\nLos aspectos más relevantes son:\n\n**Simetría** Mide la simetría de la distribución de frecuencias en torno a la media. El estadístico más utilizado es el _Coeficiente de Asimetría de Fisher_.\n\n**Apuntamiento** Mide el apuntamiento o el grado de concentración de valores en torno a la media de la distribución de frecuencias. El estadístico más utilizado es el _Coeficiente de Apuntamiento o Curtosis_.\n\n### Coeficiente de asimetría\n\n:::{#def-coeficiente-asimetria}\n## Coeficiente de asimetría muestral $g_1$\nEl _coeficiente de asimetría muestral_ de una variable $X$ es el promedio de las desviaciones de los valores de la muestra respecto de la media muestral, elevadas al cubo, dividido por la desviación típica al cubo.\n\n$$g_1 = \\frac{\\sum (x_i-\\bar x)^3 n_i/n}{s^3} = \\frac{\\sum (x_i-\\bar x)^3 f_i}{s^3}$$\n:::\n\n:::{.callout-tip}\nMide el grado de simetría de los valores de la muestra con respecto a la media muestra, es decir, cuantos valores de la muestra están por encima o por debajo de la media y cómo de alejados de esta.\n\n- $g_1=0$ indica que hay el mismo número de valores por encima y por debajo de la media e igualmente alejados de ella (simétrica).\n\n:::{.content-visible when-format=\"html\"}\n![Distribución simétrica.](img/descriptiva/distribucion_simetrica.svg)\n:::\n\n:::{.content-visible unless-format=\"html\"}\n![Distribución simétrica.](img/descriptiva/distribucion_simetrica.png)\n:::\n\n- $g_1<0$ indica que la mayoría de los valores son mayores que la media, pero los valores menores están más alejados de ella (asimétrica a la izquierda).\n\n:::{.content-visible when-format=\"html\"}\n![Distribución asimétrica hacia la izquierda.](img/descriptiva/distribucion_asimetrica_izquierda.svg)\n:::\n\n:::{.content-visible unless-format=\"html\"}\n![Distribución asimétrica hacia la izquierda.](img/descriptiva/distribucion_asimetrica_izquierda.png)\n:::\n\n- $g_1>0$ indica que la mayoría de los valores son menores que la media, pero los valores mayores están más alejados de ella (asimétrica a la derecha).\n\n:::{.content-visible when-format=\"html\"}\n![Distribución asimétrica hacia la derecha.](img/descriptiva/distribucion_asimetrica_derecha.svg)\n:::\n\n:::{.content-visible unless-format=\"html\"}\n![Distribución asimétrica hacia la derecha.](img/descriptiva/distribucion_asimetrica_derecha.png)\n:::\n:::\n\n:::{#exm-coeficiente-asimetria}\n## Datos agrupados\nUtilizando la tabla de frecuencias de la muestra de estaturas y añadiendo una nueva columna con las desviaciones de la media $\\bar x = 174.67$ cm al cubo, se tiene\n\n$$\n\\begin{array}{crrrr}\n\\hline\nX & x_i & n_i & x_i-\\bar x & (x_i-\\bar x)^3 n_i \\\\\n\\hline\n(150,160] & 155 & 2 & -19.67 & -15221.00\\\\\n(160,170] & 165 & 8 & -9.67 & -7233.85\\\\\n(170,180] & 175 & 11 & 0.33 & 0.40\\\\\n(180,190] & 185 & 7 & 10.33 & 7716.12\\\\\n(190,200] & 195 & 2 & 20.33 & 16805.14\\\\\n\\hline\n\\sum &  & 30 & & 2066.81 \\\\\n\\hline\n\\end{array}\n$$\n\n$$g_1 = \\frac{\\sum (x_i-\\bar x)^3n_i/n}{s^3} = \\frac{2066.81/30}{10.1^3} = 0.07.$$\n\nComo está cerca de 0, eso significa que la distribución de las estaturas es casi simétrica.\n:::\n\n### Coeficiente de apuntamiento o curtosis\n\n:::{#def-coeficiente-apuntamiento}\n## Coeficiente de apuntamiento muestral $g_2$\nEl _coeficiente de apuntamiento muestral_ de una variable $X$ es el promedio de las desviaciones de\nlos valores de la muestra respecto de la media muestral, elevadas a la cuarta, dividido por la desviación típica a la\ncuarta y al resultado se le resta 3.\n\n$$g_2 = \\frac{\\sum (x_i-\\bar x)^4 n_i/n}{s^4}-3 = \\frac{\\sum (x_i-\\bar x)^4 f_i}{s^4}-3$$\n:::\n\n:::{.callout-tip}\nEl coeficiente de apuntamiento mide la concentración de valores en torno a la media y la longitud de las colas de la distribución.\nSe toma como referencia la distribución normal (campana de Gauss).\n\n- $g_2=0$ indica que la distribución tienen un apuntamiento normal, es decir, la concentración de valores en torno a la media es similar al de una campana de Gauss (_mesocúrtica_).\n\n:::{.content-visible when-format=\"html\"}\n![Distribución mesocúrtica.](img/descriptiva/distribucion_mesocurtica.svg)\n:::\n\n:::{.content-visible unless-format=\"html\"}\n![Distribución mesocúrtica.](img/descriptiva/distribucion_mesocurtica.png)\n:::\n\n- $g_2<0$ indica que la distribución tiene menos apuntamiento de lo normal, es decir, la concentración de valores en torno a la media es menor que en una campana de Gauss (_platicúrtica_).\n\n:::{.content-visible when-format=\"html\"}\n![Distribución platicúrtica.](img/descriptiva/distribucion_platicurtica.svg)\n:::\n\n:::{.content-visible unless-format=\"html\"}\n![Distribución platicúrtica.](img/descriptiva/distribucion_platicurtica.png)\n:::\n\n- $g_2>0$ indica que la distribución tiene más apuntamiento de lo normal, es decir, la concentración de valores en torno a la media es menor que en una campana de Gauss (_leptocúrtica_).\n\n:::{.content-visible when-format=\"html\"}\n![Distribución leptocúrtica.](img/descriptiva/distribucion_leptocurtica.svg)\n:::\n\n:::{.content-visible unless-format=\"html\"}\n![Distribución leptocúrtica.](img/descriptiva/distribucion_leptocurtica.png)\n:::\n:::\n\n:::{#exm-coeficiente-apuntamiento}\n## Datos agrupados\nUtilizando la tabla de frecuencias de la muestra de estaturas y añadiendo una nueva columna con las desviaciones de la media $\\bar x = 174.67$ cm a la cuarta, se tiene\n\n$$\n\\begin{array}{rrrrr}\n\\hline\nX & x_i & n_i & x_i-\\bar x & (x_i-\\bar x)^4 n_i\\\\\n\\hline\n(150,160] & 155 & 2 & -19.67 & 299396.99\\\\\n(160,170] & 165 & 8 & -9.67 & 69951.31\\\\\n(170,180] & 175 & 11 & 0.33 & 0.13\\\\\n(180,190] & 185 & 7 & 10.33 & 79707.53\\\\\n(190,200] & 195 & 2 & 20.33 & 341648.49\\\\\n\\hline\n\\sum &  & 30 & & 790704.45 \\\\\n\\hline\n\\end{array}\n$$\n\n$$g_2 = \\frac{\\sum (x_i-\\bar x)^4n_i/n}{s^4} - 3 = \\frac{790704.45/30}{10.1^4}-3 = -0.47.$$\n\nComo se trata de un valor negativo, aunque cercano a 0, podemos decir que la distribución es ligeramente platicúrtica.\n\nComo se verá más adelante en la parte de inferencia, muchas de las pruebas estadísticas solo pueden aplicarse a poblaciones normales.\n\nLas poblaciones normales se caracterizan por ser simétricas y mesocúrticas, de manera que, tanto el coeficiente de asimetría como el de apuntamiento pueden utilizarse para contrastar si los datos de la muestra provienen de una población normal.\n\n:::{.callout-tip}\nEn general, se suele rechazar la hipótesis de normalidad de la población cuando $g_1$ o $g_2$ estén fuera del intervalo $[-2,2]$.\n:::\n\nEn tal caso, lo habitual es aplicar alguna transformación a la variable para corregir la anormalidad.\n\n### Distribuciones no normales\n\n#### Distribución asimétrica a la derecha no normal\nUn ejemplo de distribución asimétrica a la derecha es el ingreso de las familias.\n\n:::{.content-visible when-format=\"html\"}\n![Distribucion de los ingresos familiares de EEUU.](img/descriptiva/ejemplo_distribucion_asimetrica_derecha.svg)\n:::\n\n:::{.content-visible unless-format=\"html\"}\n![Distribucion de los ingresos familiares de EEUU.](img/descriptiva/ejemplo_distribucion_asimetrica_derecha.png)\n:::\n\n#### Distribución asimétrica a la izquierda no normal\nUn ejemplo de distribución asimétrica a la izquierda es la edad de fallecimiento.\n\n:::{.content-visible when-format=\"html\"}\n![Distribucion de la edad de fallecimiento.](img/descriptiva/ejemplo_distribucion_asimetrica_izquierda.svg)\n:::\n\n:::{.content-visible unless-format=\"html\"}\n![Distribucion de la edad de fallecimiento.](img/descriptiva/ejemplo_distribucion_asimetrica_izquierda.png)\n:::\n\n#### Distribución bimodal no normal\nUn ejemplo de distribución bimodal es la hora de llegada de los clientes de un restaurante.\n\n:::{.content-visible when-format=\"html\"}\n![Distribucion de la hora de llegada de los clientes de un restaurante.](img/descriptiva/ejemplo_distribucion_bimodal.svg)\n:::\n\n:::{.content-visible unless-format=\"html\"}\n![Distribucion de la hora de llegada de los clientes de un restaurante.](img/descriptiva/ejemplo_distribucion_bimodal.png)\n:::\n\n## Transformaciones de variables\n\nEn muchas ocasiones se suelen transformar los datos brutos para corregir alguna anormalidad de la distribución o simplemente para trabajar con unas unidades más cómodas.\n\nPor ejemplo, si estamos trabajando con estaturas medidas en metros y tenemos los siguientes valores:\n\n$$\n1.75 \\mbox{ m}, 1.65 \\mbox{ m}, 1.80 \\mbox{ m},\n$$\n\npodemos evitar los decimales multiplicando por 100, es decir, pasando de metros a centímetros:\n\n$$\n175 \\mbox{ cm}, 165 \\mbox{ cm}, 180 \\mbox{ cm},\n$$\n\nY si queremos reducir la magnitud de los datos podemos restarles a todos el menor de ellos, en este caso, 165cm:\n\n$$10\\mbox{cm}, 0\\mbox{cm}, 15\\mbox{cm},$$\n\nEstá claro que este conjunto de datos es mucho más sencillo que el original. En el fondo lo que se ha hecho es aplicar a los datos la transformación:\n\n$$Y= 100X-165$$\n\n### Transformaciones lineales\n\nUna de las transformaciones más habituales es la _transformación lineal_:\n\n$$Y=a+bX.$$\n\n\n:::{#thm-transformaciones-lineales}\nDada una variable muestral $X$, si $Y$ es la variable muestral que resulta de aplicar a $X$ la transformación lineal $Y=a+bX$, entonces\n\n\\begin{align*}\n\\bar y &= a+ b\\bar x,\\\\\ns_{y} &= |b|s_{x}\n\\end{align*}\n\nAdemás, el coeficiente de curtosis no se altera y el de asimetría sólo cambia de signo si $b$ es negativo.\n:::\n\n:::{.callout-note collapse=\"true\"}\n## Demostración\nSe deja como ejercicio.\n<!-- TODO: Demostración propiedades transformaciones lineales -->\n:::\n\n### Transformación de tipificación y puntuaciones típicas\n\nUna de las transformaciones lineales más habituales es la _tipificación_:\n\n:::{#def-variable-tipificada}\n## Variable tipificada\nLa _variable tipificada_ de una variable estadística $X$ es la variable que resulta de restarle su media y dividir por su desviación típica.\n\n$$Z=\\frac{X-\\bar x}{s_{x}}$$\n\nPara cada valor $x_i$ de la muestra, la _puntuación típica_ es el valor que resulta de aplicarle la transformación de tipificación\n\n$$z_i=\\frac{x_i-\\bar x}{s_{x}}.$$\n:::\n\n:::{.callout-tip}\nLa puntuación típica es el número de desviaciones típicas que un valor está por encima o por debajo de la media, y es útil para evitar la dependencia de una variable respecto de las unidades de medida empleadas. Esto es útil, por ejemplo, para comparar valores de variables o muestras distintas.\n:::\n\n:::{cor-propiedades-variable-tipificada}\nDada una variable muetral $X$, si $Z$ es la variable tipificada de $X$, entonces\n\n$$\\bar z = 0 \\qquad s_{z} = 1.$$\n:::\n\n:::{.callout-note collapse=\"true\"}\n## Demostración\nSe deja como ejercicio.\n<!-- TODO: Demostración propiedades tipificación. -->\n:::\n\n:::{#exm-tipificacion}\nLas notas de 5 alumnos en dos asignaturas $X$ e $Y$ son\n\n$$\n\\begin{array}{rccccccccc}\n\\mbox{Alumno:} & 1 & 2 & 3 & 4 & 5\\\\\n\\hline\nX: & 2 & 5 & 4 & \\color{red} 8 & 6 & \\qquad & \\bar x = 5 & \\quad s_x = 2\\\\\nY: & 1 & 9 & \\color{red} 8 & 5 & 2 & \\qquad & \\bar y = 5 & \\quad s_y = 3.16\\\\\n\\hline\n\\end{array}\n$$\n\n_¿Ha tenido el mismo rendimiento el cuarto alumno en la asignatura $X$ que el tercero en la asignatura $Y$?_\n\nPodría parecer que ambos alumnos han tenido el mismo rendimiento puesto que tienen la misma nota, pero si queremos ver el rendimiento relativo al resto del grupo, tendríamos que tener en cuenta la dispersión de cada muestra y medir sus puntuaciones típicas:\n\n$$\n\\begin{array}{cccccc}\n\\mbox{Alumno:} & 1 & 2 & 3 & 4 & 5\\\\\n\\hline\nX: & -1.50 & 0.00 & -0.50 & \\color{red}{1.50} & 0.50 \\\\\nY: & -1.26 & 1.26 & \\color{red}{0.95} & 0.00 & -0.95\\\\\n\\hline\n\\end{array}\n$$\n\nEs decir, el alumno que tiene un 8 en $X$ está $1.5$ veces la desviación típica por encima de la media de $X$, mientras que el alumno que tiene un 8 en $Y$ sólo está $0.95$ desviaciones típicas por encima de la media de $Y$. Así pues, el primer alumno tuvo un rendimiento superior al segundo.\n\nSiguiendo con el ejemplo anterior y considerando ambas asignaturas, _¿cuál es el mejor alumno?_\n\nSi simplemente se suman las puntuaciones de cada asignatura se tiene:\n\n$$\\begin{array}{rccccc}\n\\mbox{Alumno:} & 1 & 2 & 3 & 4 & 5\\\\\n\\hline\nX: & 2 & 5 & 4 & 8 & 6 \\\\\nY: & 1 & 9 & 8 & 5 & 2 \\\\\n\\hline\n\\sum & 3 & \\color{red}{14} & 12 & 13 & 8\n\\end{array}\n$$\n\nEl mejor alumno sería el segundo.\n\nPero si se considera el rendimiento relativo tomando las puntuaciones típicas se tiene\n\n$$\n\\begin{array}{rccccc}\n\\mbox{Alumno:} & 1 & 2 & 3 & 4 & 5\\\\\n\\hline\nX: & -1.50 & 0.00 & -0.50 & 1.50 & 0.50 \\\\\nY: & -1.26 & 1.26 & 0.95 & 0.00 & -0.95\\\\\n\\hline\n\\sum & -2.76 & 1.26 & 0.45 & \\color{red}{1.5} & -0.45\n\\end{array}\n$$\n\nY el mejor alumno sería el cuarto.\n:::\n\n#### Transformaciones no lineales\n\nLas transformaciones no lineales son también habituales para corregir la anormalidad de las distribuciones.\n\nLa transformación $Y=X^2$ comprime la escala para valores pequeños y la expande para valores altos, de manera que es muy útil para corregir asimetrías hacia la izquierda.\n\n:::{.content-visible when-format=\"html\"}\n![Transformación cuadrática.](img/descriptiva/transformacion_cuadratica.svg)\n:::\n\n:::{.content-visible unless-format=\"html\"}\n![Transformación cuadrática.](img/descriptiva/transformacion_cuadratica.png)\n:::\n\nLas transformaciones $Y=\\sqrt x$, $Y= \\log X$ y $Y=1/X$ comprimen la escala para valores altos y la expanden para valores pequeños, de manera que son útiles para corregir asimetrías hacia la derecha.\n\n:::{.content-visible when-format=\"html\"}\n![Transformación logarítmica.](img/descriptiva/transformacion_logaritmica.svg)\n:::\n\n:::{.content-visible unless-format=\"html\"}\n![Transformación logarítmica.](img/descriptiva/transformacion_logaritmica.png)\n:::\n\n### Variables clasificadoras o factores\n\nEn ocasiones interesa describir el comportamiento de una variable, no para toda la muestra, sino para distintos grupos de individuos correspondientes a las categorías de otra variable conocida como **variable clasificadora** o **factor**.\n\n:::{#exm-factores}\nDividiendo la muestra de estaturas según el sexo se obtienen dos submuestras:\n\n$$\n\\begin{array}{lll}\n\\hline\n\\mbox{Mujeres} & & 173, 158, 174, 166, 162, 177, 165, 154, 166, 182, 169, 172, 170, 168. \\\\\n\\mbox{Hombres} & & 179, 181, 172, 194, 185, 187, 198, 178, 188, 171, 175, 167, 186, 172, 176, 187. \\\\\n\\hline\n\\end{array}\n$$\n:::\n\nHabitualmente los factores se usan para comparar la distribución de la variable principal para cada categoría del factor.\n\n:::{#exm-diagramas-agrupados-factores}\nLos siguientes diagramas permiten comparar la distribución de estaturas según el sexo.\n\n:::{.content-visible when-format=\"html\"}\n![Histograma de estaturas por sexo.](img/descriptiva/histograma_estatura_sexo.svg)\n:::\n\n:::{.content-visible unless-format=\"html\"}\n![Histograma de estaturas por sexo.](img/descriptiva/histograma_estatura_sexo.png)\n:::\n\n:::{.content-visible when-format=\"html\"}\n![Diagramas de cajas de estaturas por sexo.](img/descriptiva/diagrama_caja_estatura_sexo.svg)\n:::\n\n:::{.content-visible unless-format=\"html\"}\n![Diagramas de cajas de estaturas por sexo.](img/descriptiva/diagrama_caja_estatura_sexo.png)\n:::\n:::\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}